### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/mod-duel-reset#1]
- [x] add module base with configuration
- [x] add health/mana script
- [x] added a temporary basic cooldown reset
- [ ] move health/mana reset core APIs to script
- [ ] convert the cooldowns reset script

**Comment by falzard** [comment]
>     DuelResetHealthMana
>         Description: Reset health and mana before duel starts and restore them when duel ends.
>         Default:     1  - (Enabled)

It says it restores cooldown when duel ends but it does not.

**Comment by FrancescoBorzi** [comment]
that's because " *convert the cooldowns reset script* " is missing
